name: music_player
description: Basic mp3 player
publish_to: 'none'

version: 0.0.7+10

environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  path: ^1.9.1
  rxdart: ^0.28.0
  just_audio: ^0.10.5
  file_picker: ^10.2.1
  fluttertoast: ^8.2.12
  audio_session: ^0.2.2
  path_provider: ^2.1.5
  skeletonizer: ^2.1.0+1
  cupertino_icons: ^1.0.2
  audio_service: ^0.18.18
  json_annotation: ^4.9.0
  new_version_plus: ^0.1.1
  package_info_plus: ^8.3.1
  flex_color_picker: ^3.7.1
  shared_preferences: ^2.5.3
  permission_handler: ^11.3.4
  flutter_rust_bridge: 2.11.1
  flutter_native_splash: ^2.4.6
  audio_metadata_reader: ^1.4.2
  flutter_launcher_icons: ^0.14.4
  just_audio_background: ^0.0.1-beta.17
  flutter_riverpod: ^3.0.3
  riverpod_generator: ^3.0.3
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^3.0.3
  rust_lib_music_player:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.0
  freezed: ^3.1.0
  custom_lint: ^0.8.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.10.0
  riverpod_lint: ^3.0.3
  integration_test:
    sdk: flutter

flutter_launcher_icons:
  image_path_android: "assets/icons/note_2.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/note_2.png
