name: Music Player Android Test, Build & Store

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install FVM
        run: |
          curl -fsSL https://fvm.app/install.sh | bash
          echo "$HOME/fvm/bin" >> $GITHUB_PATH

      - name: Install Flutter SDK via FVM
        run: |
          VERSION=$(jq -r '.flutter' .fvmrc)
          echo "Installing Flutter $VERSION via FVM"
          fvm install $VERSION
          fvm use $VERSION --force

      - name: FVM Flutter Doctor
        run: fvm flutter doctor

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Generate code
        run: fvm flutter pub run build_runner build --delete-conflicting-outputs

      # - name: Run tests
      #   run: fvm flutter test

      - name: Set up Java (required for Play upload + Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/release.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build Android App Bundle
        run: fvm flutter build appbundle --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload to Google Play (Internal Track)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.cenkt.music_player
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: draft

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
